[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/auth/twitch/login"
  to = "/.netlify/functions/twitch-login"
  status = 200

[[redirects]]
  from = "/api/auth/twitch/callback"
  to = "/.netlify/functions/twitch-callback"
  status = 200

[[redirects]]
  from = "/api/auth/twitch/me"
  to = "/.netlify/functions/twitch-me"
  status = 200

[[redirects]]
  from = "/api/auth/twitch/logout"
  to = "/.netlify/functions/twitch-logout"
  status = 200
